environment:
  matrix:
    - platform: x86
      nodejs_version: "5"
      arch: "32"
    - platform: x64
      nodejs_version: "5"
      arch: "64"

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version $env:platform)
  - npm -g install npm@2
  - set PATH=%APPDATA%\npm;%PATH%
  - appveyor DownloadFile https://github.com/jimpark/unsis/releases/download/2.50.0/nsis-2.50.0-Unicode-setup.exe
  - nsis-2.50.0-Unicode-setup.exe /S /D=C:\Program Files (x86)\NSIS
  - set PATH="C:\Program Files (x86)\NSIS";%PATH%
  - npm install
  
build: off

test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  #- npm test

after_test:
  - npm run release
  - ps: "cd releases"
  - ren *.exe *.win%arch%.exe
  
artifacts:
- path: releases\*.win32.exe
- path: releases\*.win64.exe

deploy:
- provider: GitHub
  tag: ChangeMe
  release: autobin draft release
  auth_token:
    secure: bPlHCdaxjgVJXAW2CooVSnyJr0pHg+qu2HdsS27HgVDRRXlTO+mgMk7V3+N/OTe+
  artifact: /.*\.exe/
  draft: true
  on:
    branch: master
